apiVersion: apps/v1
kind: Deployment
metadata:
  name: anand-deployment
  namespace: default
spec:
  replicas: 2
  selector:  
    matchLabels:
      app: nginx
  template:
    metadata:
      labels: 
        app: nginx
    spec: 
      containers:
        -  name: anand-container
           image: nginx:1.14.2
           ports:
             -  containerPort: 80
      
